Create model with associations and features
igorkol91/ror-social-scaffold pull request #3
Opened 2021-06-16 15:11 UTC by ZeenatLawal

2021-06-16 15:55 UTC, igorkol91 commented
The previous milestone was approved as shown in this link we are providing https://github.com/igorkol91/ror-social-scaffold/pull/2.
Unfortunately, we still have 'changes requested' in the dashboard and although we emailed the support we still didn't get any answer.

2021-06-16 16:52 UTC, SajjadAhmad14 commented on app/views/users/_user.html.erb
> +    <% end %>
Remove this logic and add to app/helpers. [OPTIONAL]

2021-06-16 16:55 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] You have mastered Git Flow.
- [ ] PR title and summary is descriptive

## To Improve 🙏
- [ ] User1 sends friendship request to user2, but user2 is not able to see incoming request. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/pending_request.png).
- [ ] User should be able to accept friend request. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png).
- [ ] User should be able to reject friend request. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/accept_reject_friendship.png). 
- [ ] Posts timeline should include posts written by logged-in user and their friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png).
- [ ] Please add integration tests for friendship functionality.
- [ ] Please see inline comments for reference.
# Optional
- [ ] Views should have no logic. You can use app/helpers to put all of your view-related logic and render it in views.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-16 16:55 UTC, SajjadAhmad14 commented on app/views/users/show.html.erb
> +    <% end %>
Remove this logic and add to app/helpers. [OPTIONAL]

2021-06-17 09:18 UTC, ZeenatLawal commented
A logged-in user can see their received and pending friend requests only for their accounts on their profile page. We assumed the previous review missed this point that's why we are explaining this. :smile:

2021-06-17 09:47 UTC, mke2111 requested changes
# STATUS: CHANGES REQUIRED 🔴 ♻️ 

## Hey Happy Coders, 👋🏽 
**This is a great project you have going on, well-done lads and thanks for implementing the changes requested earlier on**. 

### Well-done 💯 
    1. Users can now accept and reject requests.

**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

### REQUIRED

- [x] Posts timeline should include posts written by logged-in user and their friends. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png). Right now, a user has all posts on their index page from all users even when they are not friends.

### OPTIONAL

- [ ] Once a friend request has been sent, accepted or rejected, the `Add friend` button still exists on the all users page. This isn't the expected app's behavior.
- [ ] Please add integration tests for the app's functionality. Place these tests in the features directory. 

#

### Kindly make all the requested changes and submit another CRR. 💯 

**Cheers 🍹 and Happy coding 💻** 

<hr>

Mention @mke2111 in this thread and I'll be glad to help. 😄 
### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-17 09:51 UTC, mke2111 commented
> The previous milestone was approved as shown in this link we are providing #2.
> Unfortunately, we still have 'changes requested' in the dashboard and although we emailed the support we still didn't get any answer.

Has this issue been solved? If not, reach out to the reviewer that approved that milestone. They'll know what to do and your milestone will be marked complete within a few hours.

Best regards.

2021-06-17 10:51 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coders, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The Posts timeline now has the expected behavior.

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-06-17 11:13 UTC, merged